name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: [self-hosted, linux, RISCV64]
    steps:
      - name: Clone the repo
        run: git clone https://github.com/Sh4d1/aozig.git || git -C aozig pull origin
          
      - name: Install zig
        run: mkdir zig && curl -fsSL https://ziglang.org/builds/zig-linux-riscv64-0.12.0-dev.2341+92211135f.tar.xz -o /tmp/zig.tar.xz && tar xf /tmp/zig.tar.xz -C /tmp && cp -r /tmp/zig-linux-riscv64-0.12.0-dev.2341+92211135f/* zig/ || true

      - name: Bench
        run: uname -a ; head -n 1 /etc/os-release ; echo ; cd aozig ; ../zig/zig build run -Doptimize=ReleaseFast -- bench
